### ISSUE TITLE
Fork (possible for version 2)

### ISSUE THREAD

**Issue by atiris** [Vaelek/node-google-shared-locations#1]
Hi, I created fork with updated multiple parts of [your code](<https://github.com/Vaelek/node-google-shared-locations>) and this one: [ioBroker.google-sharedlocations](<https://github.com/t4qjXH8N/ioBroker.google-sharedlocations/blob/master/main.js>).

You can [find it here](<https://github.com/atiris/node-google-shared-locations>). There might still be further changes.

There is many changes, unfortunately, I did not share them by individual committees. I just thought about using local ones first, but later I thought it might be useful for the whole library. In short, I did the following adjustments:

- full async
- some basic test (it would be good to add more)
- testing script (like demo which users can call without having to write their own code)
- added code for 2FA (only by mobile confirmation on android phone)
- after successful login it is not possible to extract user password
- output clean up (there is no reason to return duplicates)
- extended output
  - now with main user location (user id 0, some parts need to be set, maybe it is possible to detect, I don't know yet)
  - phone battery status in output
- better errors

Would you accept these changes as a merge request? If not, I will set up my own fork repository. But I think these edits could also be version 2 of your current code. 

Thanks for reply.
Jozef

**Comment by Vaelek** [comment]
Send it through and I'll gladly take a look :) I checked it out a while ago and your improvements were looking pretty good. The only thing I didn't like personally, was the removal of the additional forms of spelling for lat/long values returned as I had them in there for seamless use with other platforms that take them in one form or the other. But I can always put that back in ;)

**Comment by atiris** [comment]
OK, I will check it and send PR probably this week.
in terms of duplicate keys :) you can always put that back in or [copy this keys after call this library](<https://stackblitz.com/edit/js-qvonmu>). It is very strange to modify library instead of adapt the code that uses the library.

**Comment by Vaelek** [comment]
Sounds good, and yes, what you did there looks much better than what I had 👍

**Comment by atiris** [comment]
Because there is no development version here, I entered PR for the master. Please check if it's okay.

**Comment by atiris** [comment]
Gentle reminder. Have you had time to look at it? If you do not have time, just let me know, I will create my own package.

**Comment by Vaelek** [comment]
Sorry for the delay, merged. For as long as I've used github, that's the first PR I've had to accept so didn't want to mess it up.

**Comment by atiris** [comment]
Thanks for merge. Please, could you also update the npm package? Using git repository directly it's not as comfortable as it could be.
